### ISSUE TITLE
ValueError returned in ``get_users.py``

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#156]
When trying to load users into the django database, it returns this error:

```
[root@55b7a12ee688 data_scripts]# ./get_users.py   
Traceback (most recent call last):
  File "./get_users.py", line 69, in <module>
    birthdate=dob)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 399, in create
    obj = self.model(**kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 439, in __init__
    setattr(self, field.name, rel_obj)
  File "/usr/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 207, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "[<School: Buckingham Elementary School>]": "UserProfile.school" must be a "School" instance.
```

@alxngyn Do you know what's up/can you look into it?

**Comment by alxngyn** [comment]
@athai how did you produce the bug? steps? 

Did you run `get_schools.py` before running the `get_users.py`? I think that's what is happening

**Comment by athai** [comment]
To reproduce the bug:
1. ``docker-compose run web bash``
2. ``cd data_scripts``
3. ``./get_sites.py`` ``./get_schools.py``, ``./get_users.py``

**Comment by alxngyn** [comment]
@athai fixed and PR proposed
https://github.com/osuosl/streamwebs/pull/160

**Comment by athai** [comment]
Resolved.
