### ISSUE TITLE
Problem running ./get_all.sh on production

### ISSUE THREAD

**Issue by ramereth** [osuosl/streamwebs#414]
I was trying to deploy the site on the production instance and ran into the following issues. Any idea what might be causing it? I've added your ssh keys to the streamwebs-production user on the same host as staging so you can poke around.

I wonder if I did a partial deploy last time? I'm not sure.

``` console
$ ./get_all.sh 
Sites loaded.
Schools loaded.
Users loaded.
Macroinvertebrates loaded.
Basic info loaded.
Traceback (most recent call last):
  File "./get_required_fields.py", line 54, in <module>
    waterq = Water_Quality.objects.get(nid=row['Nid'])
  File "/home/streamwebs-production/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method                                                                                                                     return getattr(self.get_queryset(), name)(*args, **kwargs)                                                           File "/home/streamwebs-production/venv/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get          (self.model._meta.object_name, num)                                                                                streamwebs.models.MultipleObjectsReturned: get() returned more than one Water_Quality -- it returned 2!                Conductivity loaded.                                                                                                   Total solids loaded.                                                                                                   BOD loaded.                                                                                                            Ammonia loaded.
Nitrite loaded.
Nitrate loaded.
Phophates loaded.
Fecal coliform loaded.
Measurement tools loaded.
Riparian Transects loaded.
Zone 1 loaded.
Zone 2 loaded.
Zone 3 loaded.
Zone 4 loaded.
Zone 5 loaded.
Canopy Covers loaded.
Soil survey data loaded.
Duplicates renamed, uid-to-school relations made.
Duplicates renamed, uid-to-school relations made.
Traceback (most recent call last):
  File "./reset_dup_relations.py", line 29, in <module>
    related_school = School.objects.get(name=assoc_schools[i])
  File "/home/streamwebs-production/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/streamwebs-production/venv/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get
    (self.model._meta.object_name, num)
streamwebs.models.MultipleObjectsReturned: get() returned more than one School -- it returned 4!
Traceback (most recent call last):
  File "./set_schools.py", line 80, in <module>
    relation = SchoolRelations.objects.get(uid=row['Uid'])
  File "/home/streamwebs-production/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/streamwebs-production/venv/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get
    (self.model._meta.object_name, num)
streamwebs.models.MultipleObjectsReturned: get() returned more than one SchoolRelations -- it returned 2!
```

**Comment by JerryPeng0112** [comment]
I think Bailey had that problem before, I'm not sure what caused it but we restarted the database and it worked.

**Comment by ramereth** [comment]
@JerryPeng0112 "restarted the database" What does that mean exactly?

**Comment by JerryPeng0112** [comment]
@ramereth So we dropped and re-create the database.

**Comment by ramereth** [comment]
Well, I can't do that in production but I guess since this is an initial deploy I can do it and see if that fixes it. I'll let you know.

**Comment by ramereth** [comment]
This was resolved by doing a clean install. I'm not going to worry about it moving forward.
